### ISSUE TITLE
error

### ISSUE THREAD

**Issue by netopir** [Tensai75/nzbrefresh#1] opened 2024-06-24 18:27 UTC
Hello

Today i start using your programm and get this error :

NZBRefresh v0.0.0-alpha-2
Starting segment check of 61957 segments
Checking segments : done    (61957/61957) [========================================]               [2m 51s|0s]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0xe0 pc=0x289714]

goroutine 1 [running]:
github.com/Tensai75/cmpb.(*Bar).SetMessage(0x772d90?, {0x40ef8d?, 0x11?})
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/bar.go:236 +0x34
main.main()
        /home/runner/work/nzbrefresh/nzbrefresh/main.go:243 +0x33a

I am on Windows 11 x64

**Comment by netopir** [comment] 2024-06-28 07:13
New

NZBRefresh v0.0.0-alpha-2
Starting segment check of 69411 segments
Checking segments :          (8684/69411) [====>-----------------------------------]              [11s|1m 18s]
Uploading articles:                 (8/8) [========================================]                   [6s|0s]
panic: sync: negative WaitGroup counter

goroutine 253 [running]:
sync.(*WaitGroup).Add(0x6bd4e0?, 0xc00008c028?)
        /opt/hostedtoolcache/go/1.22.2/x64/src/sync/waitgroup.go:62 +0xd8
sync.(*WaitGroup).Done(...)
        /opt/hostedtoolcache/go/1.22.2/x64/src/sync/waitgroup.go:87
github.com/Tensai75/cmpb.(*Progress).render(0x6bd4e0, 0xa0?)
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/progress.go:195 +0x25d
github.com/Tensai75/cmpb.(*Progress).Start.func1()
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/progress.go:216 +0x2c
created by github.com/Tensai75/cmpb.(*Progress).Start in goroutine 1
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/progress.go:212 +0xc5

**Comment by netopir** [comment] 2024-06-28 14:16
NZBRefresh v0.0.0-alpha-2
Starting segment check of 56920 segments
Checking segments :         (40084/56920) [===========================>------------]              [1m 50s|46s]
Uploading articles:                 (4/4) [========================================]                  [26s|0s]
panic: sync: negative WaitGroup counter

goroutine 278 [running]:
sync.(*WaitGroup).Add(0xadd4e0?, 0xc000054030?)
        /opt/hostedtoolcache/go/1.22.2/x64/src/sync/waitgroup.go:62 +0xd8
sync.(*WaitGroup).Done(...)
        /opt/hostedtoolcache/go/1.22.2/x64/src/sync/waitgroup.go:87
github.com/Tensai75/cmpb.(*Progress).render(0xadd4e0, 0xa0?)
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/progress.go:195 +0x25d
github.com/Tensai75/cmpb.(*Progress).Start.func1()
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/progress.go:216 +0x2c
created by github.com/Tensai75/cmpb.(*Progress).Start in goroutine 1
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/progress.go:212 +0xc5

**Comment by netopir** [comment] 2024-06-30 14:19
NZBRefresh v0.0.0-alpha-2
Starting segment check of 81065 segments
Checking segments : done    (81065/81065) [========================================]               [1m 42s|0s]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0xe0 pc=0x3f9714]

goroutine 1 [running]:
github.com/Tensai75/cmpb.(*Bar).SetMessage(0x85d4e0?, {0x57ef8d?, 0x11?})
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/bar.go:236 +0x34
main.main()
        /home/runner/work/nzbrefresh/nzbrefresh/main.go:243 +0x33a

**Comment by Tensai75** [comment] 2024-07-04 15:38
Thanks for reporting these and please keep them comming. I currently don't have time to work on this project but will do so again so and such reports are very much appreciated!

**Comment by netopir** [comment] 2024-07-07 10:29
There is no need to rush, if some other error appears, I will write it.
But when there is no error it looks like this:

NZBRefresh v0.0.0-alpha-2
Starting segment check of 61291 segments
Checking segments : done    (61291/61291) [========================================]               [1m 49s|0s]
Uploading articles: done            (3/3) [========================================]                  [54s|0s]
Results for 'xxxx': checked: 61291 | available: 61291 | missing: 0 | refreshed: 0 | 35 connections used
Results for 'xxxxx': checked: 61291 | available: 61288 | missing: 3 | refreshed: 3 | 35 connections used
Results for 'xxxxxxxxxxx': checked: 61291 | available: 61288 | missing: 3 | refreshed: 0 | 35 connections used
Total runtime 1m49.5246946s | 1.7869508 ms/segment

**Comment by Tensai75** [comment] 2024-07-07 11:43
Thanks.

I think I have already found a [fix](https://github.com/Tensai75/cmpb/commit/16fb79fca9289a96c0c5f607eb7b4562448554bd) for the `panic: sync: negative WaitGroup counter` errors you reported (your 2nd and 3th post). But I am not sure if it will actually fix it because unfortunately I am not able to reproduce this error. I will include the fix in the next release anyway.

Regarding the other error (your first and 4th post) I have however no clue. This error obviously occures at the end, when no missing articles were found and the progress bar is drawn for the last time. Unfortunately I cannot reproduce this error either.

Regards, Tensai

**Comment by netopir** [comment] 2024-07-07 15:39
I will keep an eye out if this error appears again with posts 1 and 4.

**Comment by netopir** [comment] 2024-07-08 08:11
Hi, this error appears if you repeat the same file again.

NZBRefresh v0.0.0-alpha-2
Starting segment check of 167908 segments
Checking segments : done  (167908/167908) [========================================]              [10m 54s|0s]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0xe0 pc=0x4a9714]

goroutine 1 [running]:
github.com/Tensai75/cmpb.(*Bar).SetMessage(0x90d4e0?, {0x62ef8d?, 0x11?})
        /home/runner/go/pkg/mod/github.com/!tensai75/cmpb@v0.0.0-20240601075616-76ce7bf974ae/bar.go:236 +0x34
main.main()
        /home/runner/work/nzbrefresh/nzbrefresh/main.go:243 +0x33a

**Comment by Tensai75** [comment] 2024-07-13 03:57
all errors posted here should be fixed with https://github.com/Tensai75/nzbrefresh/releases/tag/v0.0.0-alpha-3

**Closed by Tensai75** 2024-07-13 03:57 UTC
